apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-1
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: example.local
    http:
      paths:
      - path: /app1(/|$)(.*)
        backend:
          serviceName: echoserver 
          servicePort: 80
      - path: /app2(/|$)(.*)
        backend:
          servicePort: 80
          serviceName: hello-kubernetes-paul
      - path: /argo(/|$)(.*)
        backend:
          servicePort: 443
          serviceName: argo-cd-argocd-server
