apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-1
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: example.local
    http:
      paths:
      - path: /dash(/|$)(.*)
        backend:
          serviceName: k8dash
          servicePort: 80
      - path: /
        backend:
          servicePort: 443
          serviceName: argo-cd-argocd-server

