apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: default
spec:
  clusterIP: 10.100.191.145
  clusterIPs:
  - 10.100.191.145
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: https
  - name: web
    nodePort: 30784
    port: 80
    protocol: TCP
    targetPort: 80
  - name: admin
    nodePort: 30461
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: traefik-ingress-lb
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
